apiVersion: v1
kind: Pod
metadata:
  name: go-samp
spec:
  containers:
  - name: go-samp
    image: ghcr.io/jockdarock/k8s-go-samp:v0.0.0
    resources:
      requests:
        memory: "20Mi"
        cpu: "20m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
    - containerPort: 8080