apiVersion: v1
kind: Pod
metadata:
  name: py-samp
spec:
  containers:
  - name: py-samp
    image: ghcr.io/jockdarock/k8s-py-samp:v0.0.0
    resources:
      requests:
        memory: "20Mi"
        cpu: "20m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
    - containerPort: 8082